### PR TITLE
Add a new guide and fix some old bugs

### PR DESCRIPTION
**Pull request by IMYdev**

### CODE REVIEW

**Comment by IMYdev** [comment]
The term firmware is explained in the context of Android ROM development

**Comment by PugzAreCute** [comment]
@IMYdev feel free to add yourself into the contributors json in this pr

If you want to become a member of this org, dm me

**Review by PugzAreCute — APPROVED** [review]
LGTM

**Review by PugzAreCute — CHANGES_REQUESTED** [review]
Actually, these arent content fillers, why not add them to a file in the root such as `Bringup_Glossary` or move everything into a folder called `bringup` and have a `Tutorial` and `Terms` there?

**Comment by sounddrill31** [comment]
How is this?

https://github.com/IMYdev/docs/pull/1

**Review by PugzAreCute — APPROVED** [review]
LGTM! Great job @IMYdev and @sounddrill31!
We really needed a bringup guide!

**Pull request merged**
